### ISSUE TITLE
[ENHANCEMENT] please add feature to select audios from multiple audios and selecting subtitles as well.

### ISSUE THREAD

**Issue by susil-py** [libDrive/libDrive#9] opened 2021-03-02 08:16 UTC
### Outline of feature request select audios and subtitles from video

please add feature to select audios from multiple audios and selecting subtitles as well. 
### Reason

Why do you think this would be a good addition to libDrive

**Additional information**
Add any other extra information or screenshots about the feature request here.

**Comment by eliasbenb** [comment] 2021-03-04 09:39
I've been trying to find ways the implement this, but found none. If you find anything comment your findings and references. Thanks for the suggestions.

**Comment by eliasbenb** [comment] 2021-03-11 19:30
I just got it working 😊for video quality switching
Expect this in the new update

Although subtitles I haven't figured out.

![preview](https://user-images.githubusercontent.com/54410649/110843393-ac8aab00-82c1-11eb-84c2-a995d34412cf.png)

This is what it looks like, for now 4320p means raw (original quality) and the other others are transcoded, because of an issue with plyr.io

https://github.com/libDrive/backend/commit/930edd3cd125c48e971c449509a544819aeed565
https://github.com/libDrive/frontend/commit/21b5821448f20272571f0356c99fd888a11d2b2f

**Comment by eliasbenb** [comment] 2021-03-31 11:25
> For dual audio movies ,, and exoplayer have the potency to play from multiple audio tracks..
> 
> Well for dual audio track movies exoplayer works fine in node and Android studio..
> But can say weather it will work online via js.

There is no method I'm aware of to extract audio streams from a video container, there is no mainstream browser that even supports container videos, so very unlikely that it's possible.

**Comment by eliasbenb** [comment] 2021-05-04 19:05
Since this seems to be an impossible task I'll be closing the issue.

**Closed by eliasbenb** 2021-05-04 19:05 UTC
Labels: enhancement

**Comment by dishapatel010** [comment] 2021-05-05 12:22
[KHPlayer](https://github.com/DELNEGEND/khplayer) might be helpful for many subtitles / resolutions (plyr)!

**Comment by eliasbenb** [comment] 2021-05-05 12:53
> [KHPlayer](https://github.com/DELNEGEND/khplayer) might be helpful for many subtitles / resolutions (plyr)!
> 
> [DEMO](https://khplayer.delnegend.com/others/demo/)

As already discussed, the issue is not with displaying subtitles, it's with programmatically extracting subtitles from a video stream's container. There is no method I'm aware of that can do that in JavaScript.

**Comment by dishapatel010** [comment] 2021-05-05 12:56
> > [KHPlayer](https://github.com/DELNEGEND/khplayer) might be helpful for many subtitles / resolutions (plyr)!
> > [DEMO](https://khplayer.delnegend.com/others/demo/)
> 
> As already discussed, the issue is not with displaying subtitles, it's with programmatically extracting subtitles from a video stream's container. There is no method I'm aware of that can do that in JavaScript.

else then it will help for new features! XD leave!

**Comment by eliasbenb** [comment] 2021-05-21 16:31
There is a similar discussion happening at #15 it's not exactly the same, as I already went over, extracting subtitles from a video container would be almost impossible.

I implemented a subtitle selector for client side subtitles

https://github.com/libDrive/libDrive/discussions/15#discussioncomment-769200

**Comment by susil-py** [comment] 2021-05-23 10:22
Thanks, that's great too.
I was sure you would do it.
